from django.urls import path
from . import views,API
from django.views.decorators.csrf import csrf_exempt
from.API import LocationApi,FarmApi,FarmerApi,ResourceApi,AnimalTypeApi,AnimalApi

urlpatterns = [
     path('', views.index,name='index'),
     path('farm', views.farm,name='farm'),
     path('location', views.location,name='location'),
     path('add_location', views.add_location,name='add_location'),
     path('farmer', views.farmer,name='farmer'),
     path('animal', views.animal,name='animal'),
     path('animal_type', views.type_animal,name='animal_types'),
     path('resource', views.resource,name='resources'),
     path('add_farm', views.add_farm, name='add_farm'),
     path('delete_farm/<int:farm_id>/', views.delete_farm, name='delete_farm'),
     path('edit_farm/<int:farm_id>/', views.edit_farm, name='edit_farm'),
     path('add_farmer', views.add_farmer, name='add_farmer'),
     path('delete_farmer/<int:farmer_id>/', views.delete_farmer, name='delete_farmer'),
     path('edit_farmer/<int:farmer_id>/', views.edit_farmer, name='edit_farmer'),
     path('add_animal', views.add_animal, name='add_animal'),
     path('delete_animal/<int:animal_id>/', views.delete_animal, name='delete_animal'),
     path('edit_animal/<int:animal_id>/', views.edit_animal, name='edit_animal'),
     path('add_animal_type', views.add_animal_type, name='add_animal_type'),
     path('delete_animal_type/<int:animal_type_id>/', views.delete_animal_type, name='delete_animal_type'),
     path('edit_animal_type/<int:animal_type_id>/', views.edit_animal_type, name='edit_animal_type'),
     path('add_resource', views.add_resource, name='add_resource'),
     path('delete_resource/<int:resource_id>/', views.delete_resource, name='delete_resource'),
     path('edit_resource/<int:resource_id>/', views.edit_resource, name='edit_resource'),
     path('delete_location/<int:location_id>/', views.delete_location, name='delete_location'),
     path('edit_location/<int:location_id>/', views.edit_location, name='edit_location'),
#api
     path('api/location', LocationApi().list_objects, name='location_api'),
     path('api/farm', FarmApi().list_objects, name='farm_api'),
     path('api/farmer', FarmerApi().list_objects, name='farmer_api'),
     path('api/resource', ResourceApi().list_objects, name='resource_api'),
     path('api/animal_type', AnimalTypeApi().list_objects, name='animal_type_api'),
     path('api/animal', AnimalApi().list_objects, name='animal_api'),
     path('api/add_location', LocationApi().create_object, name='add-location'), 
     
     path('api/add_farm', FarmApi().create_object, name='farm-create'),
     path('api/add_farmer', FarmerApi().create_object, name='add_farmer_api'),
     path('api/add_resource', ResourceApi().create_object, name='add_resource_api'),
     path('api/add_animal_type', AnimalTypeApi().create_object, name='add_animal_type_api'),
     path('api/add_animal', AnimalApi().create_object, name='add_animal_api'),
     path('api/delete_location/<int:instance_id>/', LocationApi().delete_object, name='location-delete'),
     path('api/delete_farm/<int:instance_id>/', FarmApi().delete_object, name='farm-delete'),
     path('api/delete_farmer/<int:instance_id>/', FarmerApi().delete_object, name='delete_farmer_api'),
     path('api/delete_resource/<int:instance_id>/', ResourceApi().delete_object, name='delete_resource_api'),   
     path('api/delete_animal_type/<int:instance_id>/', AnimalTypeApi().delete_object, name='delete_animal_type_api'), 
     path('api/delete_animal/<int:instance_id>/', AnimalApi().delete_object, name='delete_animal_api'),  
     path('api/edit_location/<int:instance_id>/', LocationApi().edit_object, name='location-edit'),
     path('api/edit_farm/<int:instance_id>/', FarmApi().edit_object, name='farm-edit'),
     path('api/edit_farmer/<int:instance_id>/', FarmerApi().edit_object, name='edit_farmer_api'),
     path('api/edit_resource/<int:instance_id>/', ResourceApi().edit_object, name='edit_resource_api'),
     path('api/edit_animal_type/<int:instance_id>/', AnimalTypeApi().edit_object, name='edit_animal_type_api'),
     path('api/edit_animal/<int:instance_id>/', AnimalApi().edit_object, name='edit_animal_api'),
]