from django.urls import path
from . import views,API

urlpatterns = [
     path('', views.index,name='index'),
     path('farm', views.farm,name='farm'),
     path('location', views.location,name='location'),
     path('add_location', views.add_location,name='add_location'),
     path('farmer', views.farmer,name='farmer'),
     path('animal', views.animal,name='animal'),
     path('animal_type', views.type_animal,name='animal_types'),
     path('resource', views.resource,name='resources'),
     path('add_farm', views.add_farm, name='add_farm'),
     path('delete_farm/<int:farm_id>/', views.delete_farm, name='delete_farm'),
     path('edit_farm/<int:farm_id>/', views.edit_farm, name='edit_farm'),
     path('add_farmer', views.add_farmer, name='add_farmer'),
     path('delete_farmer/<int:farmer_id>/', views.delete_farmer, name='delete_farmer'),
     path('edit_farmer/<int:farmer_id>/', views.edit_farmer, name='edit_farmer'),
     path('add_animal', views.add_animal, name='add_animal'),
     path('delete_animal/<int:animal_id>/', views.delete_animal, name='delete_animal'),
     path('edit_animal/<int:animal_id>/', views.edit_animal, name='edit_animal'),
     path('add_animal_type', views.add_animal_type, name='add_animal_type'),
     path('delete_animal_type/<int:animal_type_id>/', views.delete_animal_type, name='delete_animal_type'),
     path('edit_animal_type/<int:animal_type_id>/', views.edit_animal_type, name='edit_animal_type'),
     path('add_resource', views.add_resource, name='add_resource'),
     path('delete_resource/<int:resource_id>/', views.delete_resource, name='delete_resource'),
     path('edit_resource/<int:resource_id>/', views.edit_resource, name='edit_resource'),
     path('delete_location/<int:location_id>/', views.delete_location, name='delete_location'),
#api
     path('api/location', API.location_api, name='location_api'),
     path('api/farm', API.farm_api,name='farm_api'),
     path('api/farmer', API.farmer_api, name='farmer_api'),
     path('api/resource', API.resource_api, name='resource_api'),
     path('api/animal_type', API.animal_type_api, name='animal_type_api'),
     path('api/animal', API.animal_api, name='animal_api'),
     path('api/add_location', API.add_location_api, name='add_location_api'),
     path('api/add_farm', API.add_farm_api, name='add_farm_api'),
     path('api/add_farmer', API.add_farmer_api, name='add_farmer_api'),
     path('api/add_resource', API.add_resource_api, name='add_resource_api'),
     path('api/add_animal_type', API.add_animal_type_api, name='add_animal_type_api'),
     path('api/add_animal', API.add_animal_api, name='add_animal_api'),
     path('api/delete_location/<int:location_id>/', API.delete_location_api, name='delete_location_api'),
     path('api/delete_farm/<int:farm_id>/', API.delete_farm_api, name='delete_farm_api'),
     path('api/delete_farmer/<int:farmer_id>/', API.delete_farmer_api, name='delete_farmer_api'),
     path('api/delete_resource/<int:resource_id>/', API.delete_resource_api, name='delete_resource_api'),   
     path('api/delete_animal_type/<int:animal_type_id>/', API.delete_animal_type_api, name='delete_animal_type_api'), 
     path('api/delete_animal/<int:animal_id>/', API.delete_animal_api, name='delete_animal_api'),    
     path('api/edit_farm/<int:farm_id>/', API.edit_farm_api, name='edit_farm_api'),
     path('api/edit_farmer/<int:farmer_id>/', API.edit_farmer_api, name='edit_farmer_api'),
     path('api/edit_resource/<int:resource_id>/', API.edit_resource_api, name='edit_resource_api'),
     path('api/edit_animal_type/<int:animal_type_id>/', API.edit_animal_type_api, name='edit_animal_type_api'),
     path('api/edit_animal/<int:animal_id>/', API.edit_animal_api, name='edit_animal_api'),
]